// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	public class Direction
	{
		public string name;
		public float degree;

		public static Direction LEFT = new Direction (0f, "LEFT");
		public static Direction RIGHT = new Direction (180f, "RIGHT");
		public Direction (float degree, string name)
		{
			this.name = name;
			this.degree = degree;			
		}

	}

}

